name: Checkmarx Vuln-Repo

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Checkmarx Scan
        uses: checkmarx/ast-github-action@main
        id: checkmarx-scan
        with:
          base_uri: https://deu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx_tenant: accuknox-nfr

  send-to-stageAutomation:
    needs: scan
    runs-on: ubuntu-latest
    environment: Stage
    
    steps:
      - name: Send to Stage Environment
        uses: accuknox/checkmarx-accuknox-action@v1.0.0
        with:
          api_key: ${{ secrets.CX_API_KEY }}
          project_name: Pishone/vulnerable-repo
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          tenant_id: ${{ secrets.TENANT_ID }}
          ak_token: ${{ secrets.ACCUKNOX_TOKEN }}
          label_id: "checkmarx"
          upload_artifact: true

  send-to-accuknox97:
    needs: scan
    runs-on: ubuntu-latest
    environment: accuknox97
    
    steps:
      - name: Send to accuknox97 Environment
        uses: accuknox/checkmarx-accuknox-action@v1.0.0
        with:
          api_key: ${{ secrets.CX_API_KEY }}
          project_name: Pishone/vulnerable-repo
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          tenant_id: ${{ secrets.TENANT_ID }}
          ak_token: ${{ secrets.ACCUKNOX_TOKEN }}
          label_id: "checkmarx"
