name: Opengrep

on:
    push:
        paths:
            - .github/workflows/opengrep.yml
    workflow_dispatch:

jobs:
  opengrep-scan:
    name: Opengrep Security Scan
    runs-on: ubuntu-latest
    environment: Stage
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Opengrep Scan
        uses: accuknox/sast-scan-opengrep-action@1.0.0  
        with:
          accuknox_endpoint: ${{ secrets.CSPM_URL }}
          accuknox_tenant: '5'
          accuknox_label: 'opengrep'
          accuknox_token: ${{ secrets.CSPM_TOKEN }}
          input_soft_fail: true
          